// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AddComponent: typeof import('./src/components/AddComponent.vue')['default']
    AddCustomize: typeof import('./src/components/AddCustomize.vue')['default']
    AddGroupBtn: typeof import('./src/components/AddGroupBtn.vue')['default']
    AddIcon: typeof import('./src/components/AddIcon.vue')['default']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    ContentLayout: typeof import('./src/components/ContentLayout.vue')['default']
    HotModal: typeof import('./src/components/home/HotModal.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MemoModal: typeof import('./src/components/home/MemoModal.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchEngine: typeof import('./src/components/SearchEngine.vue')['default']
    WeatherModal: typeof import('./src/components/home/WeatherModal.vue')['default']
    'WeatherModal copy': typeof import('./src/components/home/WeatherModal copy.vue')['default']
  }
}

export {}
